### ISSUE TITLE
Resizetizer.NT can't find libSkiaSharp on Android in Visual Studio 2022

### ISSUE THREAD

**Issue by svaldetero** [Redth/ResizetizerNT#69]
[I know VS 2022 is preview and changing] 
Resizetizer.NT errors when trying to build in Visual Studio 2022 but works in VS 2019. Diagnostic errors show:

```
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception. ---> System.DllNotFoundException: Unable to load library 'libSkiaSharp'.
   at SkiaSharp.LibraryLoader.LoadLocalLibrary[T](String libraryName)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at SkiaSharp.SkiaApi.sk_version_get_milestone()
   at SkiaSharp.SkiaSharpVersion.get_Native()
   at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)
   at SkiaSharp.SKObject..cctor()
   --- End of inner exception stack trace ---
   at SkiaSharp.SKObject.get_Handle()
   at SkiaSharp.SKNativeObject.Dispose(Boolean disposing)
   at SkiaSharp.SKFileStream.Dispose(Boolean disposing)
   at SkiaSharp.SKNativeObject.Finalize()
```
To repro, open Sample.Android app in this repository clean and rebuild.

Inconsistently, VS 2022 would even crash just trying to open the android project after it has been Cleaned.

**Comment by ysmoradi** [comment]
I've the same issue

**Comment by r2d2rigo** [comment]
Fixed on PR #83, if you can't wait for it to be merged I also have generated a package with the changes: https://github.com/rotorsoft-ltd/ResizetizerNT/releases/tag/0.3.0-vs2022

**Comment by jor1196** [comment]
is this a long way off?

**Comment by sjorsmiltenburg** [comment]
can we expect a merge to happen, or is resizetizer dead in the water?
